spring:
   application:
      name: RatingService

   jpa:
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
         ddl-auto: update
         show-sql: true

   datasource:
      url: jdbc:postgresql://localhost:5431/LocalPost
      username: postgres
      password: postgres

server:
   port: 8083

eureka:
   client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
         defaultZone: http://localhost:8761/eureka
   instance:
      prefer-ip-address: true